theme: "hugo-PaperMod"
baseURL: https://danielbrito.netlify.app/
languageCode: en-us
title: "Daniel Brito"
paginate: 5

# googleAnalytics: UA-123-45

#minify:
   # disableXML: true
    # minifyOutput: true

params:
        homeInfoParams:
                Title: "Hi👋!"
                Content: "I created this blog to share my data science projects and my learning process. Hope you enjoy it :)" 
                
        socialIcons:
        - name: github
          url: "https://github.com/danielbrito91"
        - name: twitter
          url: "https://twitter.com/_danielbrito_"
        
        
        ShowShareButtons: true
        ShowBreadCrumbs: true
        comments: true
markup:
  goldmark:
    renderer:
      unsafe: true
